### ISSUE TITLE
Please add link to live demo

### ISSUE THREAD

**Issue by BigEd** [mattgodbolt/bbc-micro-emulation#2]
please consider adding a link to the project one-line description and to the readme.

**Comment by mattgodbolt** [comment]
I made a link to the main site on "Live demo!"; not quite sure what you mean by project one-line description and readme? What kind of thing were you thinking?

Thanks btw!

**Comment by BigEd** [comment]
In the description of the github project, you have "Slides for a presentation on jsbeeb" - I'm thinking that's a good place to add a link to http://mattgodbolt.github.io/bbc-micro-emulation

Likewise in the README.md file, the same link.  (Just to make it easier to find your online slideshow)

**Comment by mattgodbolt** [comment]
Aha of course! Thanks :)

On Tue, Jul 14, 2015 at 7:55 AM, BigEd <notifications@github.com> wrote:

> In the description of the github project, you have "Slides for a
> presentation on jsbeeb" - I'm thinking that's a good place to add a link to
> http://mattgodbolt.github.io/bbc-micro-emulation
>
> Likewise in the README.md file, the same link. (Just to make it easier to
> find your online slideshow)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mattgodbolt/bbc-micro-emulation/issues/2#issuecomment-121230932>
> .
>



-- 
Matt

**Comment by mattgodbolt** [comment]
Fixed up! Thanks again Ed :+1:
